# Drift odometry simulator
publish_ground_truth_pose: true
ground_truth_frame_suffix: "_ground_truth"
velocity_noise_frequency_hz: 0.1
velocity_noise:
  x:
    mean: 0.0
    stddev: 0.0
  y:
    mean: 0.0
    stddev: 0.0
  z:
    mean: 0.0
    stddev: 0.0
  yaw:
    mean: 0.0
    stddev: 0.0






